ICIJ/datashare-client

package.json
src/pages/BatchSearchResults.vue
yarn.lock

this replaces the the standard bootstrapvue pagination nav component on the batch search results page with the customized icij murmur pagination component

Murmur pagination component

---

src/pages/Search.vue

Simple accessibility improvement removing a transition when opening a document.

aria: remove sliding transition

---

package.json
src/components/BatchSearchForm.vue
src/components/BatchSearchTable.vue
src/lang/de.json
src/lang/en.json
src/lang/ja.json
src/main.scss
src/mixins/polling.js
src/utils/_multiselect.scss
tests/unit/specs/components/BatchSearchForm.spec.js
tests/unit/specs/components/widget/WidgetTreeMap.spec.js
yarn.lock

Related to ICIJ/datashare#992
Add [vue-multiselect](https://vue-multiselect.js.org/#sub-getting-started) with same [style](https://github.com/ICIJ/prophecies/blob/main/prophecies/apps/frontend/src/utils/_multiselect.scss) as done on ICIJ/prophecies => proposal for future steps could be to add it to murmur.

feat: add batch search projects multiselect

---

src/components/ExtractingForm.vue
tests/unit/specs/components/ExtractingForm.spec.js

Related to https://github.com/ICIJ/datashare/issues/996 to avoid the frozen effect of the form on submit

feat: add overlay spinner while submitting the form ICIJ/datashare#996

---

jest.config.js
src/filters/humanDate.js
src/filters/humanTime.js
src/pages/UserHistoryDocument.vue
src/pages/UserHistorySearch.vue
tests/unit/specs/pages/UserHistorySearch.spec.js

fixes https://github.com/ICIJ/datashare/issues/1031
This PR displays dates in the searhc history. 
We added a timezone in jest config to avoid discrepencies if tests are run on a machine in a different timezone.

Feat: add date in search history 

---

src/store/modules/search.js
tests/unit/specs/store/modules/search.spec.js

Hot fix related to c3c8c46162e92d50374b334821c3bb4fb8a7d50c

fix: exclude index and indices from reset

---

src/components/DocumentContent.vue
src/store/pipelines/SanitizeHtml.js
src/store/pipelines/index.js

fixes https://github.com/ICIJ/datashare/issues/1001 
Text highlighting was wrong because the SanitizeHtml pipeline was messing up with the offsets

fix: syntax highlighting in document search

---

src/store/modules/search.js
tests/unit/specs/store/modules/search.spec.js

Related to [this issue](https://github.com/ICIJ/datashare/issues/1045)

fix: layout is not saved when route is updated

---

src/components/widget/WidgetDocumentsByCreationDate.vue

In Insigths page: use UTC date instead of local date ICIJ/datashare#1065

fix: use UTC date instead of local date ICIJ/datashare#1065

---

src/components/DocumentContent.vue

This resolve this https://github.com/ICIJ/datashare/issues/1097.

feat: scroll up on document's page change

---

src/components/BatchSearchActions.vue
src/lang/en.json
tests/unit/specs/components/BatchSearchActions.spec.js

This PR add a link to the batch search queries endpoint with a parameter to only get the queries without results.

feat: batch search queries without results

---

src/api/index.js
src/lang/en.json
src/mode/index.js
src/pages/ProjectView.vue
src/pages/ProjectViewEdit.vue
src/pages/TaskBatchSearchViewResults.vue
src/router/index.js
src/utils/font-awesome.js
tests/unit/specs/api/index.spec.js
tests/unit/specs/pages/ProjectView.spec.js
tests/unit/specs/pages/ProjectViewEdit.spec.js

Related to https://github.com/ICIJ/datashare/issues/1111
Adds project edit tab in project page on the url `/project/local-datashare/edit` for local and embedded mode

feat: project edit

---

src/core/ComponentsMixin.js
src/core/Core.js
tests/unit/specs/core/ComponentsMixin.spec.js

This PR adds a new method to the core to retrieve and load component through a method `datashare.findComponent()`.

feat: core components finder

---

src/components/BatchSearchForm.vue
tests/unit/specs/components/BatchSearchForm.spec.js

Related to [this issue](https://github.com/ICIJ/datashare/issues/1138)

feat: restrict the fuzziness input between 0 and max 

---

package.json
src/components/SearchBar.vue
src/components/SearchBarInputDropdown.vue
src/components/SearchBarInputDropdownForProjects.vue
yarn.lock

Ensure the project dropdown is not closed after a value is selected.

feat: search bar project dropdown trigger

---

src/components/ExtractingForm.vue
src/components/InlineDirectoryPicker.vue
src/components/SearchBarInputDropdownForProjects.vue

This PR ensures the user select a path restricted to a project "source path" (https://github.com/ICIJ/datashare/issues/1149).

feat: restrict indexing to project source path

---

src/components/DocumentActions.vue
src/core/Core.js
src/lang/en.json
tests/unit/specs/components/DocumentActions.spec.js

This PR disable the download button when download is not available (https://github.com/ICIJ/datashare/issues/1166).
(with an arbitrary 9KB limit)

feat: disable download button

---

src/components/DocumentActions.vue

Fix a bug with download buttons showing as pink in the table view.

fix: allow customizing download button variant with cls

---

src/components/SearchResultsHeader.vue

This avoids loading the entire mapping for all user's projects (see https://github.com/ICIJ/datashare/issues/1204).

feat: use field endpoint for each field

---

src/components/DocumentAttachments.vue
src/components/TreeView.vue
src/components/filter/FilterBoilerplate.vue
src/components/filter/FilterFooter.vue
tests/unit/specs/components/TreeView.spec.js

Related to [this issue](https://github.com/ICIJ/datashare/issues/1201)

fix: sort called multiple times when selected

---

src/components/BatchDownloadActions.vue
src/components/TasksList.vue
src/pages/TaskBatchDownloadList.vue
tests/unit/specs/components/BatchDownloadActions.spec.js
tests/unit/specs/pages/TaskBatchDownloadList.spec.js

see ICIJ/datashare#1081 and PR ICIJ/datashare#1269

fix: batch download result

---

tests/unit/specs/utils/datashare_index_mappings.json

This PR adds the relation between the Document and the Duplicate in the mapping file

feat: adds duplicate document relation in mappings

---

src/pages/TaskBatchDownloadList.vue
tests/unit/specs/pages/TaskBatchDownloadList.spec.js

Related to [this issue](https://github.com/ICIJ/datashare/issues/1392)

fix: sort batch download list

---

src/components/BatchDownloadActions.vue
tests/unit/specs/components/BatchDownloadActions.spec.js

Related to [this issue](https://github.com/ICIJ/datashare/issues/1493)

fix: relaunch batchDownload

---

src/api/index.js
tests/unit/specs/api/index.spec.js

see https://github.com/ICIJ/datashare/issues/1623

refactor: change api endpoint for batchsearch creation/copy 

---

src/components/AppPopover/AppPopover.vue
src/components/Document/DocumentMetadata/DocumentMetadataActions.vue
src/components/Document/DocumentSharePopover/DocumentSharePopover.vue
src/components/Document/DocumentSharePopover/DocumentSharePopoverForm.vue

related to ICIJ/datashare#1863

bug: haptic copy in modal

---

bin/dmd/hooks.hbs
package.json
src/components/Document/DocumentAttachments.vue
src/components/Document/DocumentEntries/DocumentEntriesHeader.vue
src/components/Document/DocumentEntries/DocumentEntriesList.vue
src/components/Document/DocumentViewer/DocumentViewerPaginated.vue
src/components/Project/ProjectDropdownSelector/ProjectDropdownSelector.vue
src/components/Search/SearchBar/SearchBarInputDropdown.vue
src/composables/useElasticSearchQuery.js
src/views/Document/DocumentView/DocumentViewUserActions.vue
src/views/Error/Error.vue
src/views/Search/SearchSelectionAddTagsModal.vue

- Project Dropdown Selector
- Document Attachments
- Document Viewer Paginated
before 
after

refactor: migrate setup syntax
