ICIJ/datashare-client

src/components/filter/FilterBoilerplate.vue
src/components/filter/types/FilterNamedEntity.vue
tests/unit/specs/components/filter/FilterBoilerplate.spec.js
tests/unit/specs/components/filter/types/FilterNamedEntity.spec.js

Mostly remove code from the `FilterNamedEntities` component.
I also took this opportunity to add an option to `FilterBoilerplate` to disable the translation of the aggregation key (example: `FRENCH -> Français`, etc) including new tests. This allows to remove even more code from  `FilterNamedEntities` component which add to implement its own "items" slot  to avoid translating named entities.

refactor: remove ne delete button

---

src/components/LocalesMenu.vue
src/core/Core.js
src/core/I18nMixin.js
src/pages/App.vue
tests/unit/specs/components/LocalesMenu.spec.js
tests/unit/specs/core/I18nMixin.spec.js

This PR aims at fixing the persistence of the selected locale.
I used this opportunity to move the logic of loading/settings the current locale into a proper core mixin called `I18nMixin`. This mixin is now used by the `LocalesMenu` component and by the `Core` instance when configuring the app.
The non-persisting state was due to the fact that the current locale was loaded directly within the `LocalesMenu` component at mount time. So for routes where there was no `LocalesMenu` (like the modal, or the login screen), the locale was never loaded. It is now done at the `Core` level, so for every route.

fix: language ignored in modals

---

src/api/resources/Document.js
src/components/document/DocumentTabPreview.vue
src/components/document/viewers/AudioViewer.vue
src/components/document/viewers/VideoViewer.vue
src/lang/en.json
src/pages/Search.vue
src/store/modules/player.js
src/store/storeBuilder.js
tests/unit/specs/api/resources/Document.spec.js
tests/unit/specs/components/document/DocumentTabPreview.spec.js
tests/unit/specs/store/modules/player.spec.js

This feature add the support for audio player:
And a video player:
To persit the "autoplay" and "loop" options I created a `Player` store module.

feat: preview audio video

---

src/components/filter/types/FilterDateRange.vue
src/lang/en.json
src/main.scss
tests/unit/specs/components/filter/types/FilterDateRange.spec.js

This PR is related to ICIJ/datashare#981
Added 2 inputs for start/end date range picking. The date format changes according to the locale. 
UX: 
- title / alt / placeholder for helping on date format
- when fields are empty and start is filled, the ui focuses on the end field.
Fix: 
- date filters where not loaded on page load 
Screenshots:

refactor: add two inputs for date range filter

---

src/components/BatchSearchFilterDropdown.vue
src/components/BatchSearchTable.vue
tests/unit/specs/components/BatchSearchTable.spec.js

related to #234 
before:
publicationStatus dropdown list item was not highlighted when updated (selected/unselected)
after:
publicationStatus dropdown list item is highlighted when updated
why: we use the same dropdown for single value selection and multiple selection. the single value is an object with label/value therefore we need to handle the selected callback differently
:v: add test on publication status router update

bug: add published dropdown filter selected on publish state update #234

---

src/components/BatchSearchForm.vue
src/mode/index.js

[cf ICIJ/datashare](https://github.com/ICIJ/datashare/pull/1006)
We changed how the batchsearches are handled by datashare :
- for LOCAL/EMBEDDED modes we create a batchsearchloop with a memory queue
- we don't need to make difference between local/server mode
This PR also fixes a bug : when refactoring with IoC, we introduced a lower/upper case bug in the mode module.

fix: avoid startTask for batchSearch ICIJ/datashare#1005

---

src/components/BatchSearchTable.vue
src/pages/BatchSearch.vue

This is a "quick" fix.
Problem is : batchsearch polling was working when there was no batchsearch. But when there is at least one batch search, it fails. 
The root cause is because when there is no batch search, there is no `BatchSearchTable` component. When the form is submitted the store value `hasBatchSearch` is commited, and as it is mapped with the state of `BatchSearch` page, then it creates the  `BatchSearchTable` calling `mounted()` that triggers `this.fetchAndRegisterPollWithLoader()`.
When  a second BatchSearch is created, the component is not mounted another time. The inner state of `BatchSearchTable` changes because it is mapped with `total` property of the store. But it doesn't trigger the polling.
It raises several points :
- with this quick fix, when there is no batch …

fix: launch polling when total changes ICIJ/datashare#1010

---

src/store/modules/search.js
tests/unit/specs/store/modules/search.spec.js

The error described in https://github.com/ICIJ/datashare/issues/1022 is caused by the method that read search filter from the URL.
This PR takes care of resetting the search filter every time an attempt to read route parameters is done.

fix: ensure store is reseted when URL query change

---

src/api/resources/Document.js
tests/unit/specs/api/resources/Document.spec.js

On Windows, documents have the full path in their names which add difficulty for users to identify their documents.
This PR fixes this issue with the following result

fix: incorrect document basename on Windows

---

src/components/BatchSearchTable.vue
src/pages/UserHistorySearch.vue
tests/unit/specs/pages/UserHistorySearch.spec.js

fixes https://github.com/ICIJ/datashare/issues/1032
Before This PR, when a filter had several value, the history for this search would display only one badge with one value.
After this PR, one badge per value for one filter is displayed (a filter with n values is displayed in n badges):

fix(history/search): display one badge per filter value

---

src/components/ExtractingFormOcrControl.vue
src/lang/en.json
tests/unit/specs/components/ExtractingFormOcrControl.spec.js

Related to [this issue](https://github.com/ICIJ/datashare/issues/1013)
This PR adds an alert when OCR is check in indexation form.
Possible improvement : disable/grey out check button

feat: adds alert informing tesseract is missing

---

src/components/DocumentActions.vue
src/components/DocumentContent.vue
src/components/DocumentLocalSearchInput.vue
src/components/DocumentTranslatedContent.vue
src/components/SearchResultsHeader.vue
src/components/SearchResultsList.vue
src/components/document/DocumentNavbar.vue
src/lang/en.json
src/store/modules/document.js
src/store/pipelines/index.js
src/utils/strings.js
tests/unit/specs/components/DocumentActions.spec.js
tests/unit/specs/components/DocumentContent.spec.js
tests/unit/specs/components/DocumentLocalSearchInput.spec.js
tests/unit/specs/components/DocumentTranslatedContent.spec.js

Related to the bug: ICIJ/datashare#1033
And related to modifications here: https://github.com/ICIJ/datashare/pull/1043
Fixed:
- Replace virtual scroller by paginated extracted text
Added:
- Extracted text download as text file is now available under Download document
Improvement suggestions:
- Refactor document content component (DRY)
- Prevent download or display when extracted text is empty.
- Propose a better pagination UX
- Propose a better download extracted text UX
Misc: 
- when merging, I'll try to squash the PR in 2 commits: 1 for the "fixed", 1 for the "added"

fix: handle long extracted text and search occurences

---

src/components/DocumentContent.vue

This PR just move a bit of code that was conflicting with the page watch, and local search term watcher.

fix: move jump to active local search on localSearchTerm

---

src/components/filter/FilterBoilerplate.vue
src/components/filter/types/FilterPath.vue

For some reason the class indicating "dark mode" on a filter was removed. This PR restore it and fix the class of tree view link with a deep selector.

fix: path filter links color

---

src/components/DocumentContent.vue

This simply remove the pagination frame around the extracted text when there is no pagination.

feat: hide pagination frame when there is no pagination

---

src/pages/BatchDownload.vue
tests/unit/specs/pages/BatchDownload.spec.js

Hotfix to prevent batch download to show placeholder endlessly when task API is in Error or the object returned has no date property (because the datashare api for batchdownload returns an error message)

fix: catch api error and stop place holder display

---

src/components/DocumentContent.vue

This fix this bug: https://github.com/ICIJ/datashare/issues/1063
The watcher on `targetLanguage` was "recooking" extract text because we used to load content in the recooking method. Since we moved the loading to a higher level method (`activateContentSlice`) we needed to call this new method instead.

fix: ensure changing target language is reactive

---

tests/unit/specs/utils/datashare_index_settings.json
tests/unit/specs/utils/datashare_index_settings_windows.json

This PR use a different index settings to search into nested attributes of the content_translated field when doing a search without specifying the field.
Documentation about flattened field names: https://www.elastic.co/guide/en/elasticsearch/reference/current/nested.html

fix: add missing nested fields for content_translated

---

tests/unit/specs/utils/datashare_index_mappings.json
tests/unit/specs/utils/datashare_index_settings.json
tests/unit/specs/utils/datashare_index_settings_windows.json

This PR aims to modify the settings and mappings for index creation in order to make accents insensitive in document content and titles. Related to [this PR](https://github.com/ICIJ/datashare/pull/1073)

fix: make accents insensitive

---

.circleci/config.yml
bin/DOCS.COMPONENTS.hbs
bin/DOCS.HOOKS.hbs
bin/collectHooks.js
bin/collectTocForComponentsDoc.js
docgen.config.js
package.json

This PR aims at changing the repository where the Client documentation is copied.
The workflow is only running on master on CircleCI ; this PR is mostly for traceability but it cannot be tested upon merge on master.

ci: move documentation to a different repository

---

src/components/AppliedSearchFiltersItem.vue
src/pages/UserHistorySearch.vue

Bug: the negative filters were not crossed
- Add line through for excluded filter in search
- Fix negation handling in saved searches
- Remove unused read-only class

fix: add line through for negation filter in searches and history

---

src/lang/ach.json
src/lang/de.json
src/lang/en.json
src/lang/es.json
src/lang/fr.json
src/lang/ja.json
src/utils/shortkeys.json

The openAnyway shortcut was still displayed after removing document extracted text limit. This PR removes it from the list.

refactor: remove openAnyway shortcut

---

src/api/index.js
src/components/ProjectForm.vue
src/core/ProjectsMixin.js
src/lang/en.json
src/pages/Error.vue
src/pages/NewProject.vue
src/pages/Project.vue
src/router/guards.js
src/router/index.js
src/utils/strings.js
tests/unit/specs/api/index.spec.js
tests/unit/specs/components/ProjectForm.spec.js
tests/unit/specs/router/guards.spec.js
tests/unit/specs/utils/strings.spec.js

This PR adds a new page to create a project, as described in https://github.com/ICIJ/datashare/issues/1112. This page relies on a new component called `ProjectForm` which is intended to be used for issue https://github.com/ICIJ/datashare/issues/1111 as well.
* Create a new `ProjectForm` component that emits an updated project on submit ;
* Create a new `NewProject` page that receives the submitted project and send it to the API ;
* Create a new `Project` page that will hold all project pages ;
* Create a new guard called `checkMode` that can read a route's meta to limit it to specific mode ;
* Refactor `utils/strings.js` to add JSDoc and a simpler implementation of `isUrl`.
* The `ProjectForm` could benefit from a "preview" using the project thumbnail …

feat: create project form

---

src/components/BatchSearchFilterDate.vue
src/components/BatchSearchForm.vue
src/components/BatchSearchTable.vue
src/components/ProjectCards.vue
src/components/ProjectSelector.vue
src/components/filter/types/FilterProject.vue
src/core/Core.js
src/core/ProjectsMixin.js
src/pages/BatchSearchResults.vue
src/pages/Landing.vue
src/router/guards.js
tests/unit/specs/components/BatchSearchForm.spec.js
tests/unit/specs/components/ProjectCards.spec.js
tests/unit/specs/components/ProjectSelector.spec.js
tests/unit/specs/components/filter/types/FilterProject.spec.js
tests/unit/specs/core/Core.spec.js
tests/unit/specs/pages/Landing.spec.js
tests/unit/specs/router/guards.spec.js

This PR allow LOCAL mode to handle several project. For backward compatibility, SERVER mode will continue to display projects as before. In LOCAL mode, they are shown only if the user has several projects.
* Update `ProjectsMixin` with a new accessors to get `projects` and `projectNames`
* Use the new mixin accessors in `BatchSearchForm`, `BatchSearchTable`, `ProjectCard` and `ProjectSelector`
If most project display use the new "label" metadata when available, the filter on the batch searchers list will continue to display the "name". This will be solved when we'll have a proper component to display project in various places.

feat: multiple projects in local mode

---

package.json
src/api/index.js
src/components/ExtractingForm.vue
src/components/FindNamedEntitiesForm.vue
src/store/modules/indexing.js
tests/unit/specs/components/ExtractingForm.spec.js
tests/unit/specs/components/FindNamedEntitiesForm.spec.js
tests/unit/specs/store/modules/indexing.spec.js
yarn.lock

Add project selector to indexing form, and named entities finder form.
Currently the backend only take into account the `defaultProject` parameter while indexing. This allow to index files in a project but requires the task to be done (and the queue emptied) before being able to start indexing on another project.
* Boyscouting: I used this opportunity to remove the library `vuex-map-fields` which was only used in those two components. I don't think they add enough value to justify adding a dependency to the project.
* Add `defaultProject`, `reportName`, `queueName` to the requests to create the tasks
* Add project selector component to pick a project (when necessary).

feat: project indexing

---

src/components/BatchSearchActions.vue
src/components/BatchSearchCopyForm.vue
src/components/BatchSearchFilterQuery.vue
src/components/BatchSearchForm.vue
src/components/BatchSearchTable.vue
src/lang/en.json
src/pages/BatchSearch.vue
src/pages/BatchSearchList.vue
src/pages/BatchSearchResults.vue
src/pages/NewBatchSearch.vue
src/pages/Tasks.vue
src/router/index.js
tests/unit/specs/components/BatchSearchActions.spec.js
tests/unit/specs/components/BatchSearchClearFiltersButton.spec.js
tests/unit/specs/components/BatchSearchCopyForm.spec.js
tests/unit/specs/components/BatchSearchFilterQuery.spec.js
tests/unit/specs/components/BatchSearchTable.spec.js
tests/unit/specs/pages/BatchSearchList.spec.js
tests/unit/specs/pages/Tasks.spec.js

In order to anticipate on future enhancements, this PR aims at moving the Batch Search Form to a separated page (instead of a modal).
* Create a new page `NewBatchSearch` to hold the form
* Create a new page `BatchSearch` to hold all batch search related views 
* Rename `BatchSearch` to `BatchSearchList`
* Make `NewBatchSearch`, `BatchSearchList` and `BatchSearchResult` children of the same route
* Remove `BatchSearchForm` from the modal
* The `batch-search` route should never be navigated directly (it's empty), hence why I edited all links to use `batch-search-list` ;
* `NewBatchSearch` page name might be confusing although its syntax is more correct than `BatchSearchNew`.

feat: batch search form page

---

src/api/index.js
src/components/InlineDirectoryPicker.vue
src/components/ProjectForm.vue
src/core/ProjectsMixin.js
src/lang/en.json
src/pages/ProjectViewEdit.vue
tests/unit/specs/api/index.spec.js
tests/unit/specs/components/ProjectForm.spec.js
tests/unit/specs/pages/ProjectViewEdit.spec.js

Allows users in the edit form (only available in local and embedded mode) to delete a project via a button in the bottom of the form. Deleting a project is validated by a popup confirmation. 
The project form has been modified to have a delete button props on project page to show delete button. Clicking on the delete button emits a delete event with the name of the project in parameter.
Side effects that remains to handle: 
What happen when deleting last project?

feat: delete project

---

src/components/BatchSearchResultsDetails.vue
src/components/BatchSearchTable.vue
src/components/ProjectLink.vue
src/components/SearchResultsListLink.vue
src/components/document/DocumentNavbar.vue
src/components/document/DocumentTabDetails.vue
tests/unit/specs/components/BatchSearchResultsDetails.spec.js
tests/unit/specs/components/BatchSearchTable.spec.js
tests/unit/specs/components/ProjectLink.spec.js

Standardize the links to the project page in several places. This is done through a new component called `ProjectLink`.
* Create the new component `ProjectLink`
* Use the new component in the batch searches list table
* Use the new component in the batch search details
* Use the new component in the document navbar
* Use the new component in the search result item (without thumbnail)

feat: project links

---

src/store/modules/insights.js
tests/unit/specs/core/WidgetsMixin.spec.js

This PR aims at letting plugin define their own widgets (https://github.com/ICIJ/datashare/issues/1148).
The new API can be used as follow (using the same `registerWidget` method):
```js
core.registerWidget({
name: 'test',
type(WidgetEmpty) {
return class WidgetTest extends WidgetEmpty {
get component() {
return {
name: 'WidgetTest',
template: '<div>WidgetTest</div>'
}
}
}
}
})
```

feat: allow widgets settings to use a factory function or a class

---

src/api/resources/Document.js
src/components/ProjectLink.vue
src/components/ProjectThumbnail.vue
src/components/document/DocumentTabDetails.vue
src/lang/ach.json
src/lang/de.json
src/lang/en.json
src/lang/es.json
src/lang/fr.json
src/lang/ja.json
tests/unit/specs/components/document/DocumentTabDetails.spec.js

To resolve [#1144](https://github.com/ICIJ/datashare/issues/1144), this PR uses a `b-table` to list a document's metadata. This allow build-in sort features and simplify the implementation. This new table also includes input with copy button for usability. Finally, the PR removes the "show more" button which wasn't adding any value to the user experience.

feat: use b-table to list metadata

---

src/components/BatchSearchFilterQuery.vue
src/components/ProjectThumbnail.vue
src/components/SearchBar.vue
src/components/SearchBarInput.vue
src/components/SearchBarInputDropdown.vue
src/components/SearchBarInputDropdownForField.vue
src/components/SearchBarInputDropdownForProjects.vue
src/lang/en.json
src/pages/Landing.vue
tests/unit/specs/components/BatchSearchFilterQuery.spec.js
tests/unit/specs/components/SearchBar.spec.js
tests/unit/specs/components/SearchBarInputDropdown.spec.js
tests/unit/specs/components/SearchBarInputDropdownForProjects.spec.js

This PR aims at making more obvious which project is currently selected in the search bar. This should also solve https://github.com/ICIJ/datashare/issues/1116 at the same time.
* refactor: make the `SearchBarInputDropdown` more generic ;
* feat: create a new `SearchBarInputDropdownForProjects` to hold the new dropdown ;
* feat: create a new `SearchBarInputDropdownForFields` to hold the existing field dropdown ;

feat: project dropdown in search bar

---

src/components/document/DocumentTabDetails.vue
tests/unit/es_utils.js
tests/unit/specs/components/document/DocumentTabDetails.spec.js

**Goal**
Currently in the document details, the basename of the document is displayed as document name instead of the tika resourcename. Consequently, the document and its embedded docs share the same document name. The PR fix this by displaying the resource name.

fix: displays resourcename instead of basename in doc tab details

---

src/api/index.js
src/components/MountedDataLocation.vue
src/components/SearchBarInputDropdownForProjects.vue
src/store/modules/indexing.js
tests/unit/specs/store/modules/indexing.spec.js

This PR uses the new endpoint to delete all projects (https://github.com/ICIJ/datashare/issues/1146).
* feat: use the new `DELETE` `/api/project` endpoint 
* refactor: move projects deletion and batch searches deletion to different methods
* feat: ensure default project is re-created after the delete
* feat ensure user settings (including projects) are reloaded after the delete
* fix: ensure on default project is used in the search store after the delete

feat: delete all projects from the sidebar

---

src/components/MountedDataLocation.vue

Ensure the "tree view" available from the "mounted data point" (in the sidebar) is show statistics for all projects, not only `local-datashare` (https://github.com/ICIJ/datashare/issues/1156).

fix: use all user's projects

---

src/components/ExtractingForm.vue
src/components/FindNamedEntitiesForm.vue
src/components/ProjectForm.vue
src/lang/en.json
src/pages/ProjectList.vue
src/pages/ProjectNew.vue
src/pages/ProjectView.vue
src/pages/ProjectViewAddDocuments.vue
src/pages/ProjectViewDocumentExtract.vue
src/pages/ProjectViewFindNamedEntities.vue
src/pages/TaskAnalysisList.vue
src/router/index.js

This PR resolves: ICIJ/datashare#1160 and resolves  ICIJ/datashare#1159
It adds in local mode:
- a button on the project page to create a new project 
- a tab to launch index task AKA "add documents" per project
- a tab to launch named entities extraction AKA "find named entities" per project
This involves the refactoring of the tasks forms to made display them as pages instead of modal with props change:
- dark background option
- project name option to directly select the concerned project
- add of a submit event to handle toast notifications when the task is launched
Fix: 
In `FindNamedEntitiesForm.vue` the radio button was previously not selected due to lowercase/uppercase mismatch of the string CORENLP.
Screenshots:

feat: new project page

---

src/components/TreeView.vue
tests/unit/specs/components/TreeView.spec.js

This overrides the selected paths in the tree view to make sure they all ends with a path separator (`/`). This should fix [#1190](https://github.com/ICIJ/datashare/issues/1190).

feat: ensure tree view returns directory paths

---

src/components/ExtractingForm.vue

The `projectName` prop was missing from the ExtractingForm component which led to the unability to preselect a project (causing [#1196](https://github.com/ICIJ/datashare/issues/1196)).

fix: restore missing prop

---

src/components/DocumentContent.vue

This PR removes loading adjacent slices on a document view. Loading previous and next slices was legacy from the previous implementation of the "extracted text" view. It is not needed anymore.

refactor: remove usage of adjacent slices

---

src/components/BatchSearchForm.vue

This PR ensures that the default selected projects in a new batch search are the same as the selected one in the general search (@see https://github.com/ICIJ/datashare/issues/1208).

feat: ensure active projects are pre-selected in BS form

---

src/components/BatchSearchResultsFilters.vue
src/components/BatchSearchResultsTable.vue
src/pages/TaskBatchSearchViewResults.vue
src/router/index.js
tests/unit/specs/components/BatchSearchResultsFilters.spec.js

This ensure we can click on a query from a batch search to be redirected to the general search page.
* fix: use the correct name in the route property ("indices" instead of "index")
* refactor: use the "indices" property so it's always a string

fix: batch search query route

---

src/api/index.js
src/components/UserHistorySaveSearchForm.vue
src/lang/en.json
src/pages/UserHistorySavedSearchList.vue

Allow rename of saved searches in the save searches list
related to [#1203](https://github.com/ICIJ/datashare/issues/1203)
The list of saved searches:
Before saving :
After saving, the title of the search is updated in background, and modal is closed:

feat: add rename saved search

---

package.json
src/api/elasticsearch.js
src/components/ColumnChartPicker.vue
src/components/filter/FilterBoilerplate.vue
src/components/filter/types/FilterAbstract.vue
src/components/filter/types/FilterDateRange.vue
src/components/filter/types/FilterRecommendedBy.vue
src/components/filter/types/FilterStarred.vue
src/components/widget/WidgetDocumentsByCreationDate.vue
src/router/index.js
src/store/filters/FilterDate.js
src/store/filters/FilterDateRange.js
src/store/filters/FilterNamedEntity.js
src/store/filters/FilterText.js
src/store/filters/index.js
tests/unit/setup.js
tests/unit/specs/components/ColumnChartPicker.spec.js
tests/unit/specs/components/widget/WidgetDocumentsByCreationDate.spec.js
tests/unit/specs/store/modules/searchfilters.spec.js
yarn.lock

Add an histogram range picker on the creation date filter and creation date widget (see [#1041](https://github.com/ICIJ/datashare/issues/1041)).
* chore: upgrade to Murmur 3.9.3 with the new `RangePicker` componet
* feat: add new `ColumnRangePicker` component
* feat: use the `ColumnRangePicker` component in `FilterDateRange`
* feat: use the `ColumnRangePicker` component in `WidgetDocumentByCreationDate`
[Screencast from 18-10-2023 16:03:54.webm](https://github.com/ICIJ/datashare-client/assets/471176/b3269016-d2b4-4efe-8d75-e94e06ed60d3)
[Screencast from 18-10-2023 16:04:44.webm](https://github.com/ICIJ/datashare-client/assets/471176/4b8b4e69-2cd2-47a3-89de-a434b8908e1d)

feat: histogram picker

---

src/components/widget/WidgetDocumentsByCreationDate.vue
src/components/widget/WidgetDuplicates.vue
src/components/widget/WidgetFieldFacets.vue
src/components/widget/WidgetListGroup.vue
src/components/widget/WidgetNames.vue
src/components/widget/WidgetText.vue
src/components/widget/WidgetTreeMap.vue
src/lang/en.json
src/pages/ProjectViewInsights.vue
src/store/widgets/WidgetFieldFacets.js
src/store/widgets/index.js
tests/unit/specs/components/widget/WidgetFieldFacets.spec.js
tests/unit/specs/components/widget/WidgetListGroup.spec.js
tests/unit/specs/components/widget/WidgetText.spec.js

This PR adds 3 news widgets to explore value facets for "authors", "content type" and "language". All those widgets use the same `WidgetFieldFacets` class and display an horizontal
bar chart next to the value (see https://github.com/ICIJ/datashare/issues/1226).
* feat: new  `WidgetFieldFacets` class and component
* feat: remove `card-header` from all widgets for lighter display
* feat: narrow the spacing between widgets

feat: new facet widgets for "authors", "content types" and "languages"

---

src/api/index.js
src/components/SearchResultsHeader.vue
tests/unit/specs/api/index.spec.js
tests/unit/specs/components/SearchResultsHeader.spec.js

Before merge: 
:rocket: Update getBatchSearches query to use GET verb and query params API endpoint
:sandwich: Side refactor : Create getMappings API method

refactor: cache get batch search list on polling

---

src/components/MountedDataLocation.vue
src/components/TreeView.vue
src/components/widget/WidgetDiskUsage.vue
src/components/widget/WidgetDocumentsByCreationDate.vue
src/components/widget/WidgetFileBarometer.vue
src/lang/en.json
tests/unit/specs/components/TreeView.spec.js
tests/unit/specs/components/widget/WidgetDocumentsByCreationDate.spec.js

This PR aims at making all widgets on the search page linking to the search (see https://github.com/ICIJ/datashare/issues/1229).
* feat: add link to files on disk filter from `WidgetFileBarometer`
* feat: add link to path filter from `TreeView` in `WidgetDiskUsage`
* feat: add link to creation date filter from `WidgetDocumentsByCreationDate`

feat: search from the widgets in project page

---

src/pages/DocumentView.vue

This feature give the ability to browse documents tabs by using URL query params `tab` with the value `extracted-text`, `preview` ... user can use previous / next from the browser

feat: add document tab navigation by url

---

src/components/TaskItemStatus.vue

Add error message back in the black box when a task fails

fix: display batch search error message

---

src/components/SearchDocumentNavbar.vue
src/components/SearchResultsGrid.vue
src/components/SearchResultsListLink.vue
src/components/SearchResultsTable.vue
src/lang/en.json
src/pages/DocumentView.vue
src/store/modules/search.js
tests/unit/specs/components/SearchResultsListLink.spec.js
tests/unit/specs/pages/DocumentView.spec.js

Related to https://github.com/ICIJ/datashare/issues/1359
Behavior choices:
* The tab is "saved" in vuex module "search". 
* The tab is kept in memory even when clearing the search
Additional fixes:
- add shortcuts back on previous/next tab selection
- add shortcuts back on pressing escape while a document is opened to close it.

feat: add tab save

---

src/components/BatchSearchForm.vue
src/router/index.js
src/utils/settings.js
src/utils/shortkeys.json

Some documentation links changed, e.g. section `all` moved to `usage`, so links from the right panel no longer work. I fixed links to articles about search and addition of new documents.

Fixed broken links to documentation

---

src/components/Button/ButtonReset.vue
src/components/PageSettings/PageSettings.vue
src/components/Settings/SettingsGeneral/SettingsGeneral.vue
src/composables/useTaskSettings.js
src/core/Core.js
src/lang/en.json
src/store/modules/app.js
src/views/Project/ProjectList/ProjectListSettings.vue
src/views/Search/SearchHistory/SearchHistoryList/SearchHistoryListSettings.vue
src/views/Search/SearchSaved/SearchSavedList/SearchSavedListSettings.vue
src/views/Search/SearchSettings.vue
src/views/Task/TaskBatchSearch/TaskBatchSearchQueryListSettings.vue
src/views/Task/TaskBatchSearch/TaskBatchSearchQueryResultListSettings.vue
src/views/Task/TaskListSettings.vue
tests/unit/specs/store/modules/app.spec.js

Linked to https://github.com/ICIJ/datashare/issues/1785 
Each page settings can be reset to default directly from the current view

feat : reset settings

---

src/components/Document/DocumentCarousel/DocumentCarousel.vue

prevent carrousel to take the all width of the document page
before:
after

style: update `DocumentCarousel` layout styling
